---
collections:
  - name: community.general
    version: 7.2.0
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
  - name: kubernetes.core
    version: 2.4.0
  # https://github.com/kewlfft/ansible-aur
  - name: kewlfft.aur

roles:
  # Galaxy v3.3.0 not working: https://github.com/PyratLabs/ansible-role-k3s/issues/196
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  # https://github.com/geerlingguy/ansible-role-docker
  - name: geerlingguy.docker
