---
all:
  children:
    docker:
      hosts:
        gertrude:
          ansible_host: 10.1.2.11
          zpool: pond

        mars:
          ansible_host: 10.1.2.21

        bogota:
          ansible_host: 10.1.2.10
          snapraid: true
          fstab_lines:
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1-part1    /mnt/parity1  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi2-part1    /mnt/parity2  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi3-part1    /mnt/parity3  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi4-part1    /mnt/disk1  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi5-part1    /mnt/disk2  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi6-part1    /mnt/disk3  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi7-part1    /mnt/disk4  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi8-part1    /mnt/disk5  xfs defaults  0 0
            - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi9-part1    /mnt/disk6  xfs defaults  0 0

    proxmox:
      hosts:
        # tars:
        #   ansible_host: 10.1.2.17
        baja:
          ansible_host: 10.1.2.18
        harambe:
          ansible_host: 10.1.2.16
          disk_passthrough_vmid: 104
          # passthrough_disks:
          #   # parity1
          #   - /dev/disk/by-id/ata-HGST_HUH728060ALE600_2QG15S0R
          #   # parity2
          #   - /dev/disk/by-id/ata-ST10000NE0008-2JM101_ZPW0MSQL
          #   # parity3
          #   - /dev/disk/by-id/ata-WDC_WD101EFBX-68B0AN0_VHG5TJRM
          #   # disk1
          #   - /dev/disk/by-id/ata-TOSHIBA_HDWT360_98R0A036FB1G
          #   # disk2
          #   - /dev/disk/by-id/ata-HGST_HDN724030ALE640_PK2234P9K44G5Y
          #   # disk3
          #   - /dev/disk/by-id/ata-HGST_HDN724030ALE640_PK2234P9K4M70Y
          #   # disk4
          #   - /dev/disk/by-id/ata-HGST_HDN724030ALE640_PK2234P9K4M5SY
          #   # disk5
          #   - /dev/disk/by-id/ata-ST3000DM001-1ER166_Z502ZJH6
          #   # disk6
          #   - /dev/disk/by-id/ata-HGST_HDN726060ALE610_NAGWMN6Y
          fan2go_config:
            fans:
              - id: chassis_1
                hwmon:
                  platform: nct6791-isa-0
                  index: 1
                neverStop: true
                curve: chassis_curve
                minPwm: 8
                maxPwm: 45
              - id: chassis_2
                hwmon:
                  platform: nct6791-isa-0
                  index: 2
                neverStop: true
                curve: chassis_curve
                minPwm: 8
                maxPwm: 45
              - id: chassis_3
                hwmon:
                  platform: nct6791-isa-0
                  index: 3
                neverStop: true
                curve: chassis_curve
                minPwm: 8
                maxPwm: 45
            sensors:
              - id: cpu_package
                hwmon:
                  platform: coretemp-isa-0
                  index: 1
              - id: mobo
                hwmon:
                  platform: nct6791-isa-0
                  index: 1
              - id: drive
                hwmon:
                  platform: drivetemp-scsi-0-80
                  index: 1
            curves:
              - id: cpu_curve
                linear:
                  sensor: cpu_package
                  steps:
                    - "40": 0
                    - "70": 18
                    - "90": 45
              - id: mobo_curve
                linear:
                  sensor: mobo
                  steps:
                    - "40": 0
                    - "70": 18
                    - "90": 45
              - id: drive_curve
                linear:
                  sensor: drive
                  steps:
                    - "40": 0
                    - "70": 18
                    - "90": 45
              - id: chassis_curve
                function:
                  type: average
                  curves:
                    - cpu_curve
                    - mobo_curve
                    - drive_curve
            statistics:
              enabled: false
              port: 9000
            api:
              enabled: false

    remote:
      hosts:
        bastion:
