---
session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: '{{ env "SECRET_EXTERNAL_DOMAIN" }}_session'
      domain: '{{ env "SECRET_EXTERNAL_DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "SECRET_EXTERNAL_DOMAIN" }}'
      default_redirection_url: 'https://{{ env "SECRET_EXTERNAL_DOMAIN" }}'

access_control:
  default_policy: &policy two_factor
  networks:
    - name: internal
      networks: ['{{ env "CLUSTER_CIDR" }}', '{{ env "NODE_CIDR" }}', '{{ env "HOME_CIDR" }}']
  rules: []

identity_providers:
  oidc:
    jwks:
      - algorithm: RS256
        key: |-
          {{- env "OIDC_JWKS_KEY" | nindent 10 }}
    cors:
      endpoints: [authorization, token, revocation, introspection]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_name: Grafana
        client_id: grafana
        # docker run authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
        client_secret: '{{ env "GRAFANA_OAUTH_CLIENT_HASHED_SECRET" }}'
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups, email]
        redirect_uris: ['https://grafana.{{ env "SECRET_INTERNAL_DOMAIN" }}/login/generic_oauth']
        userinfo_signed_response_alg: none
      - client_name: pgAdmin
        client_id: pgadmin
        client_secret: '{{ env "PGADMIN_OAUTH_CLIENT_HASHED_SECRET" }}'
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, email]
        redirect_uris: ['https://pgadmin.{{ env "SECRET_INTERNAL_DOMAIN" }}/oauth2/authorize']
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_basic
      - client_id: minio
        client_name: MinIO
        client_secret: '{{ env "MINIO_OAUTH_CLIENT_HASHED_SECRET" }}'
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        redirect_uris: ['https://minio.{{ env "SECRET_INTERNAL_DOMAIN" }}/oauth_callback']
        scopes: [openid, profile, email, groups]
        userinfo_signed_response_alg: none
      - client_name: Miniflux
        client_id: miniflux
        client_secret: '{{ env "MINIFLUX_OAUTH_CLIENT_HASHED_SECRET" }}'
        public: false
        authorization_policy: *policy
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups, email]
        redirect_uris: ['https://rss.{{ env "SECRET_EXTERNAL_DOMAIN" }}/oauth2/oidc/callback']
        userinfo_signed_response_alg: none
      - client_id: mealie
        client_name: Mealie
        public: true
        authorization_policy: *policy
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris: ['https://recipes.{{ env "SECRET_EXTERNAL_DOMAIN" }}/login']
        scopes: [openid, email, profile, groups]
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'none'
