---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/external
  - ../../../database/cloudnative-pg/app/secret.sops.yaml
  - ../../../database/dragonfly/app/secret.sops.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yaml=./resources/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
