---
kubescape_version: 2.0.164
kubescape_target: ubuntu
kubescape_download_url: https://github.com/armosec/kubescape/releases/download/v{{ kubescape_version }}/kubescape-{{ kubescape_target }}-latest
kubescape_bin_path: /usr/local/bin/kubescape
