---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: privatebin-public
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: kyverno
      namespace: kyverno
  values:
    image:
      repository: docker.io/privatebin/nginx-fpm-alpine
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      PHP_TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8080
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      data:
        enabled: true
        existingClaim: appdata
        mountPath: /srv/data
        subPath: privatebin/data
      conf:
        enabled: true
        type: configMap
        name: privatebin-public-config
        mountPath: /srv/cfg/conf.php
        subPath: conf.ini
        readOnly: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # read-only for the public interface
          # Alternative: https://github.com/PrivateBin/PrivateBin/wiki/Restrict-upload-using-NGINX
          nginx.ingress.kubernetes.io/cors-allow-methods: GET
          nginx.ingress.kubernetes.io/configuration-snippet: |
            limit_except GET {
              deny all;
            }
          # https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-to-make-privatebin-work-when-using-cloudflare-for-ddos-protection
          # no-transform tells Cloudflare and others to not change the content of
          # the file and thus breaking SRI.
          # https://developers.cloudflare.com/cache/about/cache-control#other
          # nginx.ingress.kubernetes.io/server-snippet: |
          #   location ~ \.js$ {
          #     add_header Cache-Control "public, max-age=3600, must-revalidate, no-transform";
          #     try_files $uri $uri/ =404;
          #   }
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: content-paste
        hosts:
          - host: &host "copy.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: privatebin-public-config
