# https://hub.docker.com/_/nextcloud
#
# Alternative file hosting:
# - https://github.com/SergiX44/XBackBone
# - https://syncthing.net/
# - https://github.com/cshum/imagor
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: kyverno
      namespace: kyverno
    - name: ingress-nginx
      namespace: networking
    - name: nextcloud-postgres
      namespace: default
    - name: nextcloud-redis
      namespace: default
  values:
    image:
      # https://hub.docker.com/_/nextcloud
      repository: docker.io/library/nextcloud
      tag: 24.0.6-fpm
    env:
      TZ: "${TIMEZONE}"
      NEXTCLOUD_ADMIN_USER:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: ADMIN_USERNAME
      NEXTCLOUD_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: ADMIN_PASSWORD
      NEXTCLOUD_TRUSTED_DOMAINS: "cloud.${PUBLIC_DOMAIN}"
      SMTP_HOST: maddy.comms.svc.cluster.local
      SMTP_PORT: 2525
      SMTP_AUTHTYPE: PLAIN
      MAIL_FROM_ADDRESS: "${SMTP_USER}"
      POSTGRES_HOST: nextcloud-postgres.default.svc.cluster.local
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: POSTGRES_PASSWORD
      REDIS_HOST: nextcloud-redis.default.svc.cluster.local
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: REDIS_PASSWORD
      NEXTCLOUD_DATA_DIR: /data
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    persistence:
      data:
        enabled: true
        existingClaim: appdata
        subPath:
          - path: nextcloud/html
            mountPath: /var/www/html
          - path: nextcloud/data
            mountPath: /data
          # https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212
          - path: nextcloud/redis-session.ini
            mountPath: /usr/local/etc/php/conf.d/redis-session.ini
      redis-config:
        enabled: true
        mountPath: /var/www/html
        existingClaim: appdata
        subPath: nextcloud
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: cloud-outline
        hosts:
          - host: &host "cloud.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: *app

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-postgres
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: library/postgres
      tag: "14"
    env:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: POSTGRES_PASSWORD
      POSTGRES_DB: nextcloud
      PGDATA: /var/lib/postgresql/data
    podSecurityContext:
      runAsUser: "${SECURITY_CONTEXT_RUN_AS_USER}"
      runAsGroup: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
      fsGroup: "${SECURITY_CONTEXT_FS_GROUP}"
    service:
      main:
        ports:
          http:
            port: 5432
    persistence:
      data:
        enabled: true
        mountPath: /var/lib/postgresql/data
        existingClaim: appdata
        subPath: nextcloud_db
    podAnnotations:
      secret.reloader.stakater.com/reload: nextcloud

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-redis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: docker.io/library/redis
      tag: "7"
    command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
    env:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: nextcloud
            key: REDIS_PASSWORD
    persistence:
      data:
        enabled: true
        path: /data
        existingClaim: appdata
        subPath: nextcloud_redis
    service:
      main:
        ports:
          http:
            port: 6379
    podAnnotations:
      secret.reloader.stakater.com/reload: nextcloud
