---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${PUBLIC_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "${PUBLIC_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${PUBLIC_DOMAIN}"
  dnsNames:
    - "${PUBLIC_DOMAIN}"
    - "*.${PUBLIC_DOMAIN}"
