---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - appdata-pvc.yaml
  - media-pvc.yaml
  - audiobookshelf
  - bazarr
  - calibre
  - calibre-web
  - nzbget
  - openbooks
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - snapraid-runner
  - sonarr
  - tdarr
  - youtubedl-material
