---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - network-policy.yaml
  - helm-release.yaml
commonLabels:
  app.kubernetes.io/name: pod-gateway-downloads
  app.kubernetes.io/instance: downloads-gateway
