# https://flores.eken.nl/running-unifi-controller-on-k8s/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      PUID: "${SECURITY_CONTEXT_RUN_AS_USER}"
      PGID: "${SECURITY_CONTEXT_RUN_AS_GROUP}"
    persistence:
      data:
        enabled: true
        mountPath: /config
        existingClaim: appdata
        subPath: unifi
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${LB_UNIFI_ADDR}"
        ports:
          # Web admin
          http:
            port: 8443
          # device communication
          device-comm:
            enabled: true
            port: 8080
            protocol: TCP
          # STUN
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          # AP discovery
          ap-discovery:
            enabled: true
            port: 10001
            protocol: UDP
          # 'Make controller discoverable on L2 network' option
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
          # mobile throughput test
          mobile-test:
            enabled: true
            port: 6789
            protocol: TCP
          # Remote syslog port
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          # guest portal redirect ports
          guest-portal-https:
            enabled: false
            port: 8843
            protocol: TCP
          guest-portal-http:
            enabled: false
            port: 8880
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: lan-pending
        hosts:
          - host: &host "unifi.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    nodeSelector:
      kubernetes.io/arch: amd64
